# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
[
  "Bram Aarts",
  "Huseyin Akdis",
  "Okan Altunbucak",
  "Luc Alzer",
  "Boy van Amelsfoort",
  "Saïd Ayhoun",
  "Chanel Balendonck",
  "Roger Baur",
  "Wilfried Beerens",
  "Mirjam Beijers",
  "Luciano Belfi",
  "Mieke Benders",
  "Ellen Berden",
  "Hai Berden",
  "Jac Berden",
  "Loek Berden",
  "Niels Besseling",
  "Anita van den Beuken",
  "Andy Beurskens",
  "Maurice Beurskens",
  "Hans de Bijl",
  "René Bloem",
  "Werner Bloemen",
  "Sam Bolderdijk",
  "Frank Bons",
  "Freek Boonen",
  "David Boonstra",
  "Susan Born - Joosten",
  "José Bos - van Horck",
  "Britt van der Bosch",
  "Maroan Bouadli-Arfaoui",
  "Ralph Bouman",
  "Jolanda in de Braek",
  "Claudia Brouwer - Franssen",
  "Johan Bruijnen",
  "Remco Bukkems",
  "René Camps",
  "Lisa Chickowsky",
  "Michel Claassen",
  "Cor Coenen",
  "Gé Coenen",
  "Frank Colemont",
  "Paul Coolegem",
  "Chantalle Coppus - Golsteijn",
  "Fred Coppus",
  "Bram Cox",
  "Ivo Cox",
  "Ryan Craig",
  "Berni Cremers",
  "Ruud Cuijpers",
  "Geert Daemen",
  "John Damhuis",
  "Sonja Dassen - Theunissen",
  "Ron Dautzenberg",
  "Hans Denessen",
  "Nicole Derichs - Vullings",
  "Dolf Derichs",
  "Luc Derks",
  "Paul Derks",
  "Chris van Deur",
  "Henk van Dijck",
  "Hay Dings",
  "Marco Dircks",
  "Margret Doesborgh - Broekman",
  "Maurice Dohmen",
  "Luc Douben",
  "Sabine Drost - Koolwijk",
  "Roetje Duijf",
  "Filiz Durmus",
  "Fred Engelen",
  "Annemarie Engels",
  "Timothy van der Eyken",
  "Jan Faessen",
  "Richard Faessen",
  "Martin Fagas",
  "Linda Feck",
  "Ellen Fila",
  "Corné Geerts",
  "Puck Geurts - van den Beld",
  "Abdel Ghanane",
  "Len Gielen",
  "Marco Gielen",
  "Rico Gielen",
  "René Giesbertz",
  "Sandra Gommans - van Peer",
  "Mariet Gommans",
  "Jarco Grapendaal",
  "Gerard Graventein",
  "Sabine van Groenendaal",
  "Erik de Groot",
  "Jakob Gutsch",
  "Nina Gutsch",
  "Youri Haagen",
  "Coen Hanssen",
  "Jeroen Hanssen",
  "Nanneke Hanssen",
  "Victoria van Happen - Hackl",
  "Swetlana Hartmann",
  "Jos van Hees",
  "Edith Hendrikman",
  "Reanne Hendriks",
  "Rebecca Hendriks",
  "Yvonne Hendrix",
  "Luc van Hensberg",
  "Daniëlla Hensen",
  "Frank Hermans",
  "Theo Hermans",
  "Hans Hesen",
  "Jan van Heukelom",
  "Jack Heumassej",
  "Thijs Holtman",
  "Kostan Holys",
  "Hans Huntjens",
  "Gilbert Idink",
  "Maikel IJzermans",
  "Jacqueline Jacobs van 't Land",
  "Jurgen Jacobs",
  "Erik Jakobs",
  "Jesse Jansen",
  "Jos Jansen",
  "Thijs Jansen",
  "Anouk Janssen",
  "Anke Janssen",
  "Carlos Janssen",
  "Liënne Janssen",
  "Nick Joosten",
  "Anna Julich",
  "Krzysztof Kaleja",
  "Mireille van Kan",
  "Rick Kappert",
  "Bart Kessels",
  "Anita Keunen - Huys",
  "Manuela Kiszela",
  "Ronald Kivits",
  "Cihan Kocaöz",
  "Lukasz Köhler",
  "Mariëlle van Kollenburg - de Martelaere",
  "Annet Komans - Gielen",
  "Sandra Konings",
  "Danny Koolen",
  "Marcel Koppers",
  "Michael Kramer",
  "José Kusters - Raets",
  "Andreas Lange",
  "Fred Lemmen",
  "William Lemmen",
  "Ron Lenders",
  "Ruud van Lier",
  "Raymond van der Linde",
  "Dolf Linssen",
  "Tim Litjens",
  "Peter ten Lohuis",
  "Jop Lommen",
  "Gé Lucassen",
  "Selma Luyben",
  "Christian Maas",
  "Monique Maes",
  "Margaret Magotteaux - Jeuken",
  "Anita Martens - Feuler",
  "Mark Martens",
  "Ruud Megens",
  "Mark Michels",
  "Jan Mingels",
  "Hans Moock",
  "Almir Mujanovic",
  "Wendy Nelissen",
  "Christian Nellessen",
  "Freek van Nisterdael",
  "Ben Noya",
  "Ramona Oirbans - Cartigny",
  "Alexander Oostwoud",
  "Patrick Opbroek",
  "Hans Peeters",
  "Michelle Peeters",
  "Patrick van Peij",
  "Jeroen van Pelt",
  "Dave van de Perre",
  "Davide Piedade",
  "Harmiena Pijpers",
  "Guido Platzbeecker",
  "Duangrudee Plubplueng",
  "Mustafa Punar (1)",
  "Mustafa Punar (2)",
  "Scott Raadschelders",
  "Alexander Reid",
  "Kai-Arne Reiter",
  "Bob van Rens",
  "Marloes van de Rijdt",
  "Silvie van de Rijdt",
  "Thomas Rogge",
  "Harold Roodbeen",
  "Iris Roulaux",
  "Jean Roulaux",
  "Yvonne Rutten",
  "Janusz Ryznar",
  "Erhan Sahin",
  "Ilona Savelkoul - te Baerts",
  "Kenneth Savelkoul",
  "Paul Savelkoul",
  "Jan Schaerlaeckens",
  "Peter Schell",
  "Angelique Schers",
  "Luuk Schouenberg",
  "Dennis Schouren",
  "Ruud Schuurmans",
  "Martin Selder",
  "Elly Severijns",
  "Gökmen Sezer",
  "Dorota Skowronek",
  "Pieter Smeenk",
  "Kay Smeets",
  "Ron Smits",
  "Markus Spittka",
  "Peter Stapel",
  "Hans Steeghs",
  "Lotti Steegs - Martens",
  "Roel Stevens",
  "Anja van Strien",
  "Theo Strijbos",
  "Grzegorz Stuglik",
  "Roger Suyling",
  "Seng Tan",
  "Joris Tenhagen",
  "Maarten Theulen",
  "Roland Theunissen",
  "Janny Thijssen - Ubbink",
  "Nicole Thijssen",
  "Petra Thijssen",
  "Wendy Thomassen",
  "Kamil Tomczak",
  "Jerroh Tuasuun",
  "Nurcan Ücgül",
  "Will Ummenthun",
  "Patrick Valentijn",
  "Ivonne Vallen",
  "Mirjam Vanderheijden",
  "Geert op het Veld",
  "Karin van der Ven",
  "Hans van der Ven",
  "Michelle Verbruggen",
  "Roy Verhagen",
  "Renate Verhoeven",
  "Gé Verlinden",
  "Peter Verstegen",
  "Joep Vestjens",
  "Petra Vidova",
  "Dino van der Vlies",
  "Truus de Vos",
  "Johan Vosbeek",
  "Dennis Vranken",
  "Mark Vromans",
  "July Vullings",
  "Andreas Wagner",
  "Kim Waltmans - Aarts",
  "Boy Willems",
  "Ryan van Willick",
  "Jessica Winkel",
  "Nick de Wit",
  "Andrie Witanto",
  "Doris Witjes - Ng",
  "Marcel Wittenheer",
  "Tanja Wittenheer",
  "Sing Woo",
  "Lilian van Wylick",
  "Emine Yavuz",
  "Hans van der Zanden",
  "Pim van der Zanden",
  "Wijtze van der Zee",
  "Leon Zeegers",
  "Sylwia Zientek",
  "Remco Meijer",
  "Piet Joosten",
  "Henk Vercoulen",
  "Leo Lommen",
  "Sigurt Goray",
  "Margreet Verheijen",
  "Hay Gielen",
  "Ton Pot",
  "Wiel van Mosseveld",
  "Jan Jongstra",
  "Betsie Rademaker-Hoex",
  "Jaap Hagendoorn",
  "Jeu Craenmehr"

].each do |collega|
  User.create!(name: collega,unique_code:Digest::MD5.hexdigest(Time.now.to_s + rand(999).to_s)[0..7])
  end